In [ ]:
# Probability basics
# JAGR
# Python code to generate a geometric sequence

import numpy as np
import matplotlib.pyplot as plt
p = 1/2
n = np.arange(1,10)
X = np.power(p,n)
plt.bar(n,X)
plt.show()

In [5]:
# Python code to compute (N choose K) and K!
from scipy.special import comb, factorial
n = 10
k = 2
comb(n, k)
#factorial(k)

np.float64(45.0)

In [6]:
# Python code to perform an inner product
import numpy as np
x = np.array([1,0,-1])
y = np.array([3,2,0])
z = np.dot(x,y)
k = np.cross(x,y)
print(z)
print(k)

3
[ 2 -3  2]


In [7]:
# Python code to compute the norm
import numpy as np
x = np.array([1,0,-1])
x_norm = np.linalg.norm(x)
print(x_norm)

1.4142135623730951


In [8]:
# Python code to compute the weighted norm
import numpy as np
W = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([[2],[-1],[1]])
z = np.dot(x.T, np.dot(W,x))
print(z)

[[12]]


In [9]:
# Python code to compute a matrix inverse
import numpy as np
X      = np.array([[1, 3], [-2, 7], [0, 1]])
XtX    = np.dot(X.T, X)
XtXinv = np.linalg.inv(XtX)
print(X)
print(XtX)
print(XtXinv)

[[ 1  3]
 [-2  7]
 [ 0  1]]
[[  5 -11]
 [-11  59]]
[[0.33908046 0.06321839]
 [0.06321839 0.02873563]]


In [10]:
# Python code to solve X beta = y
import numpy as np
X      = np.array([[1, 3], [-2, 7], [0, 1]])
y      = np.array([[2],[1],[0]])
beta   = np.linalg.lstsq(X, y, rcond=None)[0]
print(X)
print(y)
print(beta)

[[ 1  3]
 [-2  7]
 [ 0  1]]
[[2]
 [1]
 [0]]
[[0.82183908]
 [0.37356322]]
